apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-normal-pod
spec:
  replicas: replicas_value
  selector:
    matchLabels:
      pkey: pvalue
  template:
    metadata:
      name: nginx-replica-set
      labels:
        mkey: mvalue
    spec:
      schedulerName: poseidon
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "memreq"
            cpu: "cpureq"
          limits:
            memory: "memlim"
            cpu: "cpulim"
